#19: Episode post type
PRX/cms.theworld.org pull request #33
Opened 2022-03-10 15:23 UTC by brandonhundt

Closes #19 

- Creates the episodes custom post type and sets up custom fields

## To Review

- [ ] Checkout Branch.
- [ ] Run `npm run local` (or `npm run refresh` if you want a fresh database.)
- [ ] Go to http://the-world-wp.lndo.site/.

> ...then...

- [ ] Copy a TW episode from the frontend, ensure everything has a place.
- [ ] Confirm all fields we need for the migration are set up. [Reference this spreadsheet](https://docs.google.com/spreadsheets/d/10b6bA1-RHGuNgPtczYhJJWorjS5_kvnsIBscqeJi_Qw/edit#gid=746853851)

2022-03-10 15:26 UTC, brandonhundt commented on wp-content/themes/newspack-theme/acf-json/group_622a0f70c890f.json
> +            "type": "clone",
ACF has an option to reference an already existing field in the db. Did that here for audio and broadcast date.

2022-03-10 15:28 UTC, brandonhundt commented on wp-content/themes/newspack-theme/acf-json/group_622a159a3f6be.json
> +            "label": "Stories in this episode",
Hopefully, this allows us to create a migration path for anything thats selected already. 

But maybe not necessary???

2022-03-16 16:54 UTC, rpeterman-gp requested changes

2022-03-16 19:15 UTC, brandonhundt commented on wp-content/themes/newspack-theme/acf-json/group_622a159a3f6be.json
> +                "post_type",
Fixed!

2022-03-16 19:15 UTC, brandonhundt commented on wp-content/themes/newspack-theme/acf-json/group_622a159a3f6be.json
> +            "label": "Featured Episodes",
I changed it to Related Stories, good catch.

2022-03-22 19:17 UTC, rpeterman-gp approved these changes
Nice work! :shipit:

2022-03-22 20:37 UTC, merged