#51 Creates Custom Tags taxonomies
PRX/cms.theworld.org pull request #52
Opened 2022-05-24 18:11 UTC by brandonhundt

Closes #51 

- Adds City, Continents, Countries, Person, Province or State, Region, and Social tags to posts

## To Review

- [ ] Checkout Branch.
- [ ] Run `npm run local` (or `npm run refresh` if you want a fresh database.)
- [ ] Go to http://the-world-wp.lndo.site/.

> ...then...

- [ ] Create/edit a post
- [ ] add terms to each to each of the custom taxonomies.
- [ ] Publish the post
- [ ] Confirm the values show up in Rest

2022-06-06 19:22 UTC, rpeterman-gp requested changes
Can you resave the new plugin file and address the linter requirements for the docblock comments?

2022-06-06 20:08 UTC, brandonhundt commented
@rpeterman-gp Fixed!

2022-06-06 21:34 UTC, rpeterman-gp requested changes
Can we break tw-custom-tags file up into a file per taxonomy, then use a `require_once` to bring them into the `tw-custom-tags.php` file? Would rather deal with many files with a specific focus, than one super long file.

2022-06-07 14:52 UTC, brandonhundt commented on wp-content/plugins/tw-custom-tags/tw-custom-tags.php
> +require_once('taxonomies/taxonomy-city.php');
@rpeterman-gp I've changed this file to break it out into separate files. Let me know if there are further enhancements I can make.

2022-06-09 18:10 UTC, merged